blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from main.models import NULLABLE


class Blog(models.Model):
    topic = models.CharField(max_length=250, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержание')
    preview = models.ImageField(upload_to='blog/preview/', verbose_name='Изображение', **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')
    public_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView

from blog.models import Blog


class BlogListView(ListView):
    model = Blog
    extra_context = {
        'title': 'Список наших блогов'
    }


class BlogCreateView(CreateView):
    model = Blog
    fields = ['topic', 'content', 'preview', ]
    success_url = reverse_lazy('blog:blog_list')
    extra_context = {
        'title': 'Создание блога'
    }


class BlogUpdateView(CreateView):
    model = Blog
    fields = ['content', 'preview', ]
    success_url = reverse_lazy('blog:blog_list')
    extra_context = {
        'title': 'Изменить блог'
    }


class BlogDeleteView(DeleteView):
    model = Blog
    extra_context = {
        'title': 'Удаление блога'
    }

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">
                    Удалить блог {{ object }} ?
                </h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {% if perms.blog.blog_delete %}
                    <button type="submit" class="btn btn-outline-danger">
                        Удалить
                    </button>
                    <a href="{% url 'blog:blog_list' %}" type="button" class="btn btn-outline-success">
                        Отмена
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="header mx-auto text-center">
    <h3 class="display-6">{{ title }}</h3>
</div>
<div class="col-12">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}

                    {% if object %}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                    {% else %}
                    <button type="submit" class="btn btn-primary">Создать</button>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:blog_create' %}">Добавить блог</a>
</div>
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">{{ object.topic }}</h3>
                    </div>
                    <div class="card-body">
                        <p>{{ object.preview }}</p>
                        {% if object.content %}
                            <p>{{ object.content }}</p>
                        {% endif %}
                        {% if user.is_stuff %}
                            <a href="{% url 'blog:blog_update' object.pk %}"
                            class="btn btn-sm btn-outline-secondary">Редактировать</a>

                            <a href="{% url 'blog:blog_delete' object.pk %}"
                                class="btn btn-sm btn-outline-secondary">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}