blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
# from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import RegisterView, UserUpdateView, UserListView, VerifyView, get_password, logout_view

app_name = UsersConfig.name

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('verify/', VerifyView.as_view(), name='verify'),
    path('profile/<int:pk>/', UserUpdateView.as_view(), name='profile'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('get_password/', get_password, name='get_password'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


NULLABLE = {'blank': True, 'null': True}
ACTIVE_CHOICES = [
    (True, 'Активен'),
    (False, 'Неактивен'),
]


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')
    avatar = models.ImageField(upload_to='user/', verbose_name='Аватар', **NULLABLE)
    phone = models.CharField(max_length=20, verbose_name='Телефон', **NULLABLE)
    verify_code = models.CharField(max_length=15, verbose_name='Код верификации почты', **NULLABLE)
    verify_phone = models.CharField(max_length=15, verbose_name='Код верификации телефона', **NULLABLE)
    is_active = models.BooleanField(default=False, choices=ACTIVE_CHOICES, verbose_name='Почта активирована')
    is_verify = models.BooleanField(default=False, choices=ACTIVE_CHOICES, verbose_name='Номер телефона верифицирован')
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            ('set_is_active', 'Может блокировать пользователя')
        ]

users/forms.py
from users.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'phone', 'password1', 'password2',)


class UpdateForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class ModeratorForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, TemplateView
from users.forms import RegisterForm, ModeratorForm, UpdateForm
from users.models import User
from users.services import send_sms, send_mail_user
from django.contrib.auth import get_user_model



def logout_view(request):
    logout(request)
    return redirect('users:login')


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:verify')

    def form_valid(self, form):
        new_user = form.save(commit=False)
        new_user.save()
        verify_code = User.objects.make_random_password(length=15)
        verify_phone = User.objects.make_random_password(length=15)
        new_user.verify_code = verify_code
        new_user.verify_phone = verify_phone
        new_user.save()
        result_send = send_mail_user(
            subject='Подтверждение регистрации',
            message=f' Для получения полного доступа, введите код активации: {verify_code}',
            email_list=[new_user.email]
        )

        result_sms = send_sms(phone=new_user.phone, message=verify_phone)

        print(result_send, result_sms, sep='\n\n')
        print(f'{new_user} Введите код активации: {verify_code}')
        print(f'{new_user.phone} код верификации: {verify_phone}')
        return super().form_valid(form)


class VerifyView(TemplateView):
    template_name = 'users/verify.html'

    @staticmethod
    def post(request):
        verify_pass = request.POST.get('verify_pass')
        user_code = User.objects.filter(verify_code=verify_pass).first()
        user_phone = User.objects.filter(verify_phone=verify_pass).first()
        if user_code:
            user_code.is_active = True
            user_code.save()
            result_send = send_mail_user(
                subject='Успешная активация',
                message='Код активации принят',
                email_list=[user_code.email]
            )
            print(result_send)
            return redirect('users:login')
        if user_phone:
            user_phone.is_verify = True
            user_phone.save()
            result_sms = send_sms(phone=user_phone.phone, message='Welcome')
            print(f'Верификация телефона {user_phone.phone} прошла успешно')
            print(result_sms)
            return redirect('users:login')
        else:
            return redirect('users:verify')


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = User
    success_url = reverse_lazy('users:login')

    def test_func(self):
        _user = self.request.user
        if self.request.user == self.get_object() or _user.has_perms(['users.set_is_active', ]):
            return True
        return self.handle_no_permission()

    def get_form_class(self):
        if self.request.user == self.get_object():
            return UpdateForm
        elif self.request.user.has_perm('users.set_is_active'):
            return ModeratorForm


def get_password(request):
    new_pass = request.user.objects.make_random_password(length=15)
    result_send = send_mail_user(
        subject='Новый пароль',
        message=f'Новый пароль {new_pass}',
        email_list=[request.user.email]
    )

    if result_send:
        request.user.set_password(new_pass)
        request.user.save()
        print(f'{request.user.email} - получил новый пароль - {new_pass}')
    else:
        print(f'{request.user.email} не удалось изменить пароль')

    return redirect(reverse('users:login'))


class UserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = User
    extra_context = {'title': 'Пользователи', }

    def test_func(self):
        _user = self.request.user
        if _user.has_perms(['users.set_is_active', ]):
            return True
        return self.handle_no_permission()

users/templates/users/login.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
    {% if user.is_authenticated %}
    <p>Вы уже вошли в систему</p>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
    {% else %}
    <form class="form-signin" method="post">
        {% csrf_token %}
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Вход
                </h3>
            </div>
            <div class="card-body">
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Войти</button>

            </div>
        </div>
    </form>
    {% endif %}
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                                Изменить
                            {% else %}
                                Сохранить
                            {% endif %}
                        </button>

                    </form>
                </div>
                <div class="card-footer">
                    <a class="p-2 btn btn-outline-primary" href="{% url 'users:get_password' %}">Получить новый пароль на почту</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="header mx-auto text-center">
        <h5 class="display-4">{{ title }}</h5>
    </div>
    <div class="col-12">
        <div class="row mb-3">
            {% for object in object_list %}
                <div class="col-6 mb-3">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="my-0 font-weight-normal mb-3">Пользователь: {{ object.email }}</h3>
                            {% if not object.is_active %}
                                <p>Заблокирован</p>
                            {% else %}
                                <p>Активный</p>
                            {% endif %}
                            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' object.pk%}">Редактировать</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

users/templates/users/verify.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">

            <form method="post">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            Введите код активации почты или код верификации телефона
                        </h4>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}

                        <input type="text" name="verify_pass" class="form-control" id="verify_pass" required>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock %}