blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import MailingListView, MailingCreateView, MailingUpdateView, MailingDetailView, MailingDeleteView, \
    MessageListView, MessageCreateView, MessageUpdateView, MessageDetailView, MessageDeleteView, ClientListView, \
    ClientCreateView, ClientUpdateView, ClientDeleteView, LogsListView, HomeView

app_name = MainConfig.name
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('mailing_list', MailingListView.as_view(), name='mailing_list'),
    path('create/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing_edit/<int:pk>/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailing_view/<int:pk>', MailingDetailView.as_view(), name='mailing_view'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_add/', MessageCreateView.as_view(), name='message_add'),
    path('message_edit/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),
    path('message_view/<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('client_add/', ClientCreateView.as_view(), name='client_add'),
    path('client_edit/<int:pk>', ClientUpdateView.as_view(), name='client_edit'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('logs_list/', LogsListView.as_view(), name='logs_list'),
]

main/models.py
from django.db import models
from django.utils import timezone

from users.models import User

NULLABLE = {'blank': True, 'null': True}

ACTIVE_CHOICES = [
    (True, 'Активна'),
    (False, 'Неактивна'),
]

LOG_CHOICES = [
    (True, 'Успешно'),
    (False, 'Неудача'),
]
# Create your models here.


class Client(models.Model):

    full_name = models.CharField(max_length=150, verbose_name='ФИО')
    email = models.EmailField(unique=True, verbose_name='Почта')
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Отправитель')

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиентов'
        permissions = [
            ('client_delete', 'Может удалять клиентов')
        ]


class Message(models.Model):

    subject = models.CharField(max_length=250, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Содержание')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Владелец сообщения')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'письмо'
        verbose_name_plural = 'письма'


class Mailing(models.Model):

    stat_mailing = [('Запущена', 'Запущена'),
                    ('Завершена', 'Завершена'),
                    ('Создана', 'Создана')]
    period_mailing = [('Раз в день', 'Раз в день'),
                      ('Раз в неделю', 'Раз в неделю'),
                      ('Раз в месяц', 'Раз в месяц')]
    name = models.CharField(max_length=50, verbose_name='Рассылка', **NULLABLE)
    periodicity = models.CharField(choices=period_mailing, default='Один раз в день', verbose_name='Периодичность')
    state = models.CharField(max_length=20, choices=stat_mailing, default='Запущена', verbose_name='Статус')
    client = models.ManyToManyField(Client, verbose_name='клиент')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Владелец рассылки')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение', **NULLABLE)
    start_date = models.DateTimeField(default=timezone.now, verbose_name='Начало рассылки')
    next_date = models.DateTimeField(default=timezone.now, verbose_name='Следующая рассылка')
    end_date = models.DateTimeField(verbose_name='Конец рассылки', **NULLABLE)

    is_activated = models.BooleanField(default=True, choices=ACTIVE_CHOICES, verbose_name='Активность')


    def __str__(self):
        return f'{self.name} {self.state} {self.periodicity}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        ordering = ('start_date',)
        permissions = [
            ('set_is_activated', 'Может отключать рассылку'),
            ('can_view', 'Может просматривать рассылки')
        ]


class Logs(models.Model):

    stat_mailing = [('start', 'Запущена'),
                    ('finish', 'Завершена')]
    data = models.DateTimeField(verbose_name='Дата', **NULLABLE)
    state = models.CharField(default=False, max_length=10, choices=LOG_CHOICES, verbose_name='Попытка', **NULLABLE)
    email_answer = models.BooleanField(default=False, verbose_name='Ответ от почты')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка', **NULLABLE)
    last_mailing_time = models.DateTimeField(auto_now=True, verbose_name='Время рассылки', **NULLABLE)

    def __str__(self):
        return f'{self.last_mailing_time} - {self.state}'

    class Meta:
        verbose_name = 'Лог сообщения'
        verbose_name_plural = 'Логов сообщений'

main/forms.py
from django import forms
from django.forms import DateTimeInput

from main.models import Mailing, Message, Client


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        """Стилизация формы"""
        user = kwargs.pop("user")
        super().__init__(*args, **kwargs)
        self.fields["client"].queryset = Client.objects.filter(owner=user)
        self.fields["message"].queryset = Message.objects.filter(owner=user)

    class Meta:
        model = Mailing
        exclude = ('next_date', 'owner', 'state', 'is_activated', )

        widgets = {
            'start_date': DateTimeInput(attrs={'placeholder': 'ДД.ММ.ГГГГ ЧЧ:ММ:СС', 'type': 'datetime-local'}),
            'end_date': DateTimeInput(attrs={'placeholder': 'ДД.ММ.ГГГГ ЧЧ:ММ:СС', 'type': 'datetime-local'}),
        }


class MailingModeratorForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        fields = ('is_activated',)


class MessageForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Message
        exclude = ('owner',)


class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        exclude = ('owner',)

main/views.py
import random
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog
from main.forms import MailingForm, MessageForm, ClientForm, MailingModeratorForm
from main.models import Message, Mailing, Client, Logs
from main.services import get_cache_mailing_active, get_cache_mailing_count


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('main:mailing_list')
    extra_context = {
        'title': 'Создание рассылки'
    }

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form, *args, **kwargs):
        new_mailing = form.save(commit=False)
        new_mailing.owner = self.request.user
        new_mailing.save()
        return super().form_valid(form)


class HomeView(ListView):
    model = Mailing
    template_name = 'main/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mailings_count'] = get_cache_mailing_count()
        context_data['active_mailings_count'] = get_cache_mailing_active()
        context_data['clients_count'] = len(Client.objects.all())
        blog_list = list(Blog.objects.all())
        if len(blog_list) > 3:
            random.shuffle(blog_list)
            context_data['blog_list'] = blog_list[:3]
        else:
            context_data['blog_list'] = []

        return context_data


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    success_url = reverse_lazy('main:mailing_list')

    def get_form_class(self):
        if self.request.user == self.get_object().owner:
            return MailingForm
        elif self.request.user.has_perm('main.set_is_activated'):
            return MailingModeratorForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    extra_context = {
        'title': 'Список рассылок'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if self.request.user.has_perm('main.can_view'):
            return queryset
        return queryset.filter(owner=self.request.user)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['clients'] = list(self.object.mail_to.all())
        context_data['logs'] = list(Logs.objects.filter(mailing=self.object))
        return context_data


class MailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('main:mailing_list')

    def test_func(self):
        _user = self.request.user
        if _user == self.get_object().owner or _user.has_perms(['mailing.can_delete', ]):
            return True
        return self.handle_no_permission()


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('main:message_list')
    extra_context = {
        'title': 'Создание сообщения'
    }

    def form_valid(self, form):
        new_message = form.save()
        new_message.owner = self.request.user
        new_message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('main:message_list')


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    extra_context = {
        'title': 'Список сообщений'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if self.request.user.has_perm('mailing.can_view'):
            return queryset
        return queryset.filter(owner=self.request.user)


class MessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('main:message_list')

    def test_func(self):
        if self.request.user == self.get_object().owner:
            return True
        return self.handle_no_permission()


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    extra_context = {
        'title': 'Список клиентов'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if self.request.user.has_perm('mailing.can_view'):
            return queryset
        return queryset.filter(owner=self.request.user)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main:client_list')
    extra_context = {
        'title': 'Добавить клиента'
    }

    def form_valid(self, form):
        new_client = form.save()
        new_client.owner = self.request.user
        new_client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main:client_list')

    def test_func(self):
        return self.request.user == Client.objects.get(pk=self.kwargs['pk']).owner


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('main:client_list')

    def test_func(self):
        permissions = ('main.client_delete',)
        _user = self.request.user
        _instance = self.get_object()
        if _user == _instance.owner or _user.has_perms(permissions):
            return True
        return self.handle_no_permission()


class LogsListView(ListView):
    model = Logs
    template_name = 'main/logs_list.html'

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<form method="post" class="row">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">
                    Удалить клиента {{ object }} ?
                </h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {% if user.is_authenticated %}
                    <button type="submit" class="btn btn-outline-danger">
                        Удалить
                    </button>
                    <a href="{% url 'main:client_list' %}" type="button" class="btn btn-outline-success">
                        Отмена
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        {% else %}
                            <button type="submit" class="btn btn-primary">Создать</button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'main:client_add' %}">Добавить клиента</a>
</div>
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">{{ object.full_name|title }}</h3>
                    </div>
                    <div class="card-body">
                        <p>{{ object.email }}</p>
                        {% if object.comment %}
                            <p>{{ object.comment }}</p>
                        {% endif %}
                        {% if user == object.owner %}
                            <a href="{% url 'main:client_edit' object.pk %}"
                            class="btn btn-sm btn-outline-secondary">Редактировать</a>
                            <a href="{% url 'main:client_delete' object.pk %}"
                            class="btn btn-sm btn-outline-secondary">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h3 class="display-4">Карусель</h3>

</div>
<div class="container">
    <div class="col-12">
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Всего рассылок в сервисе</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ mailings_count }}</h1>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Всего активных рассылок</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ active_mailings_count }}</h1>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Число уникальных клиентов</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ clients_count }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h3 class="display-4">Карусель&Блог</h3>
    </div>
    <div class="col-12">
        <div class="row-4">
            {% for blog in blog_list %}
            <div class="col-4">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <div class="card-header py-3">
                            <h3 class="mb-0">{{ blog.topic }}</h3>
                        </div>
                        <div class="card-body py-3">
                            <div class="mb-1 text-muted">{{ blog.public_date }}</div>
                            <p class="card-text mb-auto">{{ blog.content }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/main/logs_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>

<div class="col-12">
    <div class="row">
        {% for object in object_list %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">{{ object.mailing }}</h3>
                    </div>
                    <div class="card-body">
                        <p>{{ object.last_mailing_time }}</p>
                        <p>{{ object.state }}</p>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/main/mailing_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">

                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Название:</td>
                            <td>{{ object.name }}</td>
                        </tr>
                        <tr>
                            <td>Кому:</td>
                            <td>{{ clients }}</td>
                        </tr>
                        <tr>
                            <td>Старт рассылки:</td>
                            <td>{{ object.time_mailing }}</td>
                        </tr>
                        <tr>
                            <td>Периодичность:</td>
                            <td>{{ object.periodicity }}</td>
                        </tr>
                        <tr>
                            <td>Текущий статус:</td>
                            <td>{{ object.state }}</td>
                        </tr>
                        <tr>
                            <td>Создатель:</td>
                            <td>{{ object.owner }}</td>
                        </tr>
                    </table>

                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if perms.mailing.set_is_activated %}
                            <a href="{% url 'main:mailing_edit' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-primary">Редактировать</a>
                        {% else %}

                            <a href="{% url 'main:mailing_edit' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-primary">Редактировать</a>
                            <a href="{% url 'main:mailing_delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">

                <div class="card-body">
                    {% for log in logs %}
                        <p>{{ log }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/mailing_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12 nb-5">
    <a class="btn btn-outline-primary" href="{% url 'main:create_mailing' %}">Создать рассылку</a>
</div>
{% for object in object_list %}
<div class="card">
    <div class="card-header">
        <h3 class="my-0 font-weight-normal">{{ object.name }}</h3>
    </div>
    <div class="card-body">
        <p>{{ object.state }}<p>
        <p>{{ object.periodicity }}<p>
        <p>{{ object.client }}</p>
        <p>{{ object.owner }}</p>
        <p>{{ object.start_date }}</p>
        <p>{{ object.end_date }}</p>
        <a href="{% url 'main:mailing_edit' object.pk %}" class="btn btn-sm btn-outline-secondary">Редактирование</a>
        <a href="{% url 'main:mailing_delete' object.pk %}" class="btn btn-sm btn-outline-secondary">Удалить</a>
    </div>

    {% endfor %}
    {% endblock %}
    <!--<div class="card">-->
    <!--                <div class="card-header">-->
    <!--                    <h3 class="my-0 font-weight-normal">{{ object.topic }}</h3>-->
    <!--                </div>-->
    <!--                <div class="card-body">-->
    <!--                    <p>{{ object.subject }}</p>-->
    <!--                    <a href="{% url 'main:message_view' object.pk %}" class="btn btn-sm btn-outline-secondary" >Просмотр &raquo;</a>-->
    <!--                    <a href="{% url 'main:message_edit' object.pk %}" class="btn btn-sm btn-outline-secondary" >Редактирование</a>-->
    <!--                    <a href="{% url 'main:message_delete' object.pk %}" class="btn btn-sm btn-outline-secondary" >Удалить</a>-->
    <!--                </div>-->
    <!--    -->
    <!--    -->
    <!--    -->
    <!--    -->
    <!--    -->
    <!--    -->
    <!--    -->
    <!--    <div class="col-lg-4">-->
    <!--        <h2 class="fw-normal">{{ object.name }}</h2>-->
    <!--        <p>{{ object.state }}<p>-->
    <!--          <p>{{ object.periodicity }}<p>-->
    <!--          <p>{{ object.time_mailing }}</p>-->
    <!--        <p><a class="btn btn-secondary" href="{% url 'main:mailing_view' object.pk %}">View &raquo;</a></p>-->
    <!--      </div>-->

main/templates/main/message_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.topic }}</h4>
                </div>
                <div class="card-body">
                    <p>{{ object.subject }}</p>
                    <p>{{ object.body }}</p>
                    {% if user == object.owner %}
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'main:message_edit' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Редактировать</a>
                            <a href="{% url 'main:message_delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/message_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="header mx-auto text-center">
    <h1 class="display-5">{{ title }}</h1>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'main:message_add' %}">Создать сообщение для рассылки</a>
</div>
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
        <div class="col-6 mb-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">{{ object.topic }}</h3>
                </div>
                <div class="card-body">
                    <p>{{ object.subject }}</p>
                    <a href="{% url 'main:message_view' object.pk %}" class="btn btn-sm btn-outline-secondary" >Просмотр &raquo;</a>
                    <a href="{% url 'main:message_edit' object.pk %}" class="btn btn-sm btn-outline-secondary" >Редактирование</a>
                    <a href="{% url 'main:message_delete' object.pk %}" class="btn btn-sm btn-outline-secondary" >Удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}